# Generated by Django 4.0.2 on 2023-02-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('nom_client', models.TextField(max_length=255)),
                ('prenom_client', models.TextField(max_length=255)),
                ('email_client', models.TextField(max_length=50)),
                ('numero_client', models.TextField(max_length=10)),
                ('nomEntreprise_client', models.TextField(max_length=255)),
                ('logoEntreprise_client', models.TextField(max_length=255)),
                ('emailEntreprise_client', models.TextField(max_length=255)),
                ('numeroEntreprise_client', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('dateDebut_contrat', models.DateField()),
                ('dateFin_contrat', models.DateField()),
                ('contractant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('nom_panneau', models.TextField(max_length=255)),
                ('commune_panneau', models.TextField(max_length=255)),
                ('altitude_panneau', models.TextField(max_length=255)),
                ('longitude_panneau', models.TextField(max_length=255)),
                ('format_panneau', models.TextField(max_length=255)),
                ('prix_panneau', models.TextField(max_length=255)),
                ('contrat_panneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contrat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
