# Generated by Django 4.0.2 on 2023-02-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_client_emailentreprise_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='update_at',
        ),
    ]
