# Generated by Django 4.0.2 on 2023-02-06 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_client_created_at_remove_client_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='update_at',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='panneau',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='panneau',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
